apps/subscriptions/urls.py
from django.urls import path

from . import views


app_name = 'subscriptions'

urlpatterns = [
    path('api/active-products/', views.ProductWithMetadataAPI.as_view(), name='products_api'),
    path('', views.subscription, name='subscription_details'),
    path('demo/', views.subscription_demo, name='subscription_demo'),
    path('subscription-gated-page/', views.subscription_gated_page, name='subscription_gated_page'),

    # stripe checkout views
    path('checkout-success/', views.checkout_success, name='checkout_success'),
    path('checkout-canceled/', views.checkout_canceled, name='checkout_canceled'),

    # stripe elements views
    path('api/create_customer/', views.create_customer, name='create_customer'),
    path('subscription_success/', views.subscription_success, name='subscription_success'),

    # stripe integration views that return redirects to Stripe
    # these are the defaults
    path('stripe/create-checkout-session/', views.create_checkout_session, name='create_checkout_session'),
    path('stripe/portal/', views.create_portal_session, name='create_stripe_portal_session'),

    # stripe api views that return Stripe URLs instead of redirects
    # these can be used by JavaScript front-ends to handle the redirect from the response
    path('stripe/api/create-checkout-session/', views.CreateCheckoutSession.as_view(),
         name='api_create_checkout_session'),
    path('stripe/api/create-portal-session/', views.CreatePortalSession.as_view(), name='api_create_portal_session'),
]

apps/users/urls.py
from django.urls import path
from . import views


app_name = 'users'
urlpatterns = [
    path('profile/', views.profile, name='user_profile'),
    path('profile/upload-image/', views.upload_profile_image, name='upload_profile_image'),
    path('api-keys/create/', views.create_api_key, name='create_api_key'),
    path('api-keys/revoke/', views.revoke_api_key, name='revoke_api_key'),
]

contaq_io/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
import allauth
from rest_framework.documentation import include_docs_urls, get_schemajs_view

schemajs_view = get_schemajs_view(title="API")

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/logout', allauth.account.views.LogoutView.as_view(), name="logout"),
    path('accounts/password/change', allauth.account.views.PasswordChangeView.as_view(), name="change_password"),
    path('users/', include('apps.users.urls')),
    path('subscriptions/', include('apps.subscriptions.urls')),
    path('web/', include('apps.web.urls')),
    path('', include('apps.app.urls')),
    path('pegasus/', include('pegasus.apps.examples.urls')),
    path('pegasus/employees/', include('pegasus.apps.employees.urls')),
    path('celery-progress/', include('celery_progress.urls')),
    # API docs
    # these are needed for schema.js
    path('docs/', include_docs_urls(title='API Docs')),
    path('schemajs/', schemajs_view, name='api_schemajs'),
    # djstripe urls - for webhooks
    path("stripe/", include("djstripe.urls", namespace="djstripe")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/app/dashboard.html
{% extends "app/layout.html" %}

{% block title %}
Dashboard
{% endblock %}

{% block body %}
<style type="text/css">
#dash{
    background-color: #325ae7;
    color: white
}
</style>
<div id="top2">
    <h1>Welcome to Contaq.io!</h1>
    <p>You have <b>{{user.credits}}</b> credits remaining</p>
</div>
<div class="section-inner"><h2>How To Get Started</h2><p>
    <p>1. Go to the <a id="newsearch" href="{% url 'ecom_search' %}">e-commerce search</a> page.<br><br>
    2. Type in the e-commerce product you want to target.<br><br>
    3. When the scrape is finished, export your verified emails from the <a id="listspage" href="{% url 'lists' %}">lists page</a>.<br><br><b>You need credits to use the tool. If you don't have credits, <a id="subspage" href="{% url 'subscriptions:subscription_details' %}">get a subscription</a>.</b></p>
</p></div>
{% comment %} <div class="cols3">
    <div class="column"><iframe
        src="https://www.youtube.com/embed/tgbNymZ7vqY">
        </iframe></div>
    <div class="column">f</div>
    <div class="column">f</div>
</div> {% endcomment %}
<div class="flex-row-container">
    {% comment %} <iframe id="iframe-left" allow="fullscreen;"
        src="https://www.youtube.com/embed/JLg-K6aFZck">
        </iframe><iframe id="iframe-left" allow="fullscreen;"
        src="https://www.youtube.com/embed/2jzevCM79-Y">
        </iframe><iframe id="iframe-left" allow="fullscreen;"
        src="https://www.youtube.com/embed/MzGvaa_3Oxs">
        </iframe></div> {% endcomment %}

  </div><div class="section-inner" style="margin-top:0px">
    <div style="padding:57.14% 0 0 0;position:relative;"><iframe src="https://player.vimeo.com/video/728221355?h=9c36e26c53&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen style="position:absolute;top:0;left:0;width:100%;height:100%;" title="Contaq.io Ecom Demo"></iframe></div><script src="https://player.vimeo.com/api/player.js"></script>  </div>
{% endblock %}

templates/app/exclusions.html
{% extends "app/layout.html" %}

{% block title %}
Dashboard
{% endblock %}

{% block body %}
<style type="text/css">
#exclusions{
    background-color: #325ae7;
    color: white
} 
</style>
<div id="top2">
    <h1>Exclusions</h1>
    <p>Add websites for us to exclude during your searches.</p>
</div>
<div class="section-inner"><h2>Add your exclusions below</h2>
<p>One domain per line
    <form action="/exclusions" method="post" id="exclusions=form">{% csrf_token %}
        <textarea id="exclusions_input" style="height:150px;font-size:16px;width:100%;" name="exclusions" required placeholder="Format: website.com"></textarea>
<button type="submit">Update</button>    </form>
</p></div>
<script type="text/javascript">
    $.ajax({
        type: 'GET',
        url: "{% url 'exclusions' %}",
        success: function (response) {
            $("#exclusions_input").html(response["exclusions"])
        }
    })
</script>

{% endblock %}

templates/app/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="{% static "css/site-bulma2.css" %}">
    <link rel="stylesheet" href="{% static "css/site-base.css" %}">
    <link rel="stylesheet" href="{% static "css/app/app.css" %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=DM+Sans&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Hind+Vadodara&family=Philosopher:wght@700&family=ZCOOL+XiaoWei&display=swap" rel="stylesheet">    
    <title>{% block title %}{% endblock %} - Contaq.io</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<header>
    {% comment %} <nav>
        <ul>
            <li><a href="{% url "dashboard" %}">Dashboard</a></li>
            <li><a href="{% url "search" %}">Search</a></li>
            <li><a href="{% url "scrape" %}">Scrape</a></li>
        </ul>
    </nav> {% endcomment %}
    <div id="mySidenav" class="sidenav">
        <div id="sidenav-top">
        <div id="sidenav-img"><center><a href="{% url "dashboard" %}"><img src="https://i.imgur.com/Xyzro6r.png"></a></center></div>
        <a class="sidenav-link" id="dash" href="{% url "dashboard" %}"><i class="fa fa-fw fa-tachometer"></i><span class="sidenav-text">Dashboard</span></a>
        <a class="sidenav-link" id="ecom_search" class="negMargin" href="{% url "ecom_search" %}"><i class="fa fa-fw fa-search-plus"></i><span class="sidenav-text">E-Commerce Search</span></a>
        {% comment %} <a class="sidenav-link" id="search" class="negMargin" href="{% url "search" %}"><i class="fa fa-fw fa-search"></i><span class="sidenav-text">Local Biz Search</span></a> {% endcomment %}
        {% comment %} <a class="sidenav-link" id="scrape" class="negMargin" href="{% url "lists" %}"><i class="fa fa-fw fa-list-ul"></i><span class="sidenav-text">Lead Lists <span class="tag is-danger is-rounded" style="font-size:10px;vertical-align:text-bottom">1</span></span></a> {% endcomment %}
        <a class="sidenav-link" id="scrape" class="negMargin" href="{% url "lists" %}"><i class="fa fa-fw fa-list-ul"></i><span class="sidenav-text">Lead Lists </span></a>
        <a class="sidenav-link" id="exclusions" class="negMargin" href="{% url "exclusions" %}"><i class="fa fa-fw fa-user-times"></i><span class="sidenav-text">Exclusions</span></a>
        <a class="sidenav-link" id="subscription" class="negMargin" href="{% url "subscriptions:subscription_details" %}"><i class="fa fa-fw fa-credit-card"></i><span class="sidenav-text">Subscription</span></a>
        <a class="sidenav-link" id="profile" class="negMargin" href="{% url "users:user_profile" %}"><i class="fa fa-fw fa-user-circle"></i><span class="sidenav-text">Profile</span></a>
        <a class="sidenav-link" id="change_password" class="negMargin" href="{% url "change_password" %}"><i class="fa fa-fw fa-lock"></i><span class="sidenav-text">Change Password</span></a>
        <a class="sidenav-link" id="log_out" style="bottom:0px" class="negMargin" href="{% url "logout" %}"><i class="fa fa-fw fa-sign-out"></i><span class="sidenav-text">Log Out</span></a>
        </div>
        <div id="collapse-expand" onclick="toggleSidebar()"><i id="collapse-expand-icon" class="fa fa-fw fa-angle-double-left"></i></div>
    </div>
</header>
<body>
    <div id="top"><span id="hamburger" style="position:absolute;left:20px;font-size:20px;cursor:pointer"><i id="collapse-expand-icon" class="fa fa-fw fa-bars"></i></span><span><span id="user-name-email">{{user}}</span> {% if user.credits == 0 %}<div class="tag is-danger is-medium ">{{user.credits}} credits</div>{% else %}<div class="tag is-success is-medium ">{{user.credits}} credits</div></a>{% endif %}</span></div>
    {% block messages %}
    {% include 'web/components/messages.html' %}
  {% endblock messages %}
    {% block body %}
    {% endblock %}
    <div id="footer">
        © Copyright 2022, All Rights Reserved. Incubated at the <a style="color:navy" href="https://innovationlabs.harvard.edu/">Harvard Innovation Labs</a><br>
        Technical support or questions: <a style="color:navy" href="mailto:support@mg.contaq.io">support@mg.contaq.io</a><br>
    </div>
    <script type="text/javascript">
        {% comment %} $.ajax({
            type: 'GET',
            url: "{% url 'num_credits' %}",
            success: function (response) {
                $("num_cred").html(response["credits"])
            }
        }) {% endcomment %}
        function toggleSidebar(e) {
            if (document.getElementById("mySidenav").style['width']=="50px"){
                document.getElementById("mySidenav").style['width']="260px"
                document.getElementsByTagName("BODY")[0].style['margin-left']="260px"
                document.getElementById("collapse-expand-icon").classList.add("fa-angle-double-left")
                document.getElementById("collapse-expand-icon").classList.remove("fa-angle-double-right")
                //document.getElementById("collapse-expand").innerHTML = '''<i class="fa fa-fw fa-angle-double-left"></i>'''
                text = document.getElementsByClassName("sidenav-text")
                for (const element of text){
                    element.style['display']='inline'
                }
            }
            else{
                document.getElementById("mySidenav").style['width']="50px"
                document.getElementsByTagName("BODY")[0].style['margin-left']="50px"
                //document.getElementById("collapse-expand").innerHTML = '''<i class="fa fa-fw fa-angle-double-right"></i>'''
                document.getElementById("collapse-expand-icon").classList.add("fa-angle-double-right")
                document.getElementById("collapse-expand-icon").classList.remove("fa-angle-double-left")
                text = document.getElementsByClassName("sidenav-text")
                for (const element of text){
                    element.style['display']='none'
                }
            }
        }

            document.getElementById("hamburger").onclick = function(){
                if (document.getElementById("mySidenav").style['width']!="100%"){
                    document.getElementById("mySidenav").style['width']="100%"
                    document.getElementById("user-name-email").style["display"]="inline"
                    document.getElementById("top").style['color']="white"
                    document.getElementById("top").style['background-color']="#1b1d2a"
                    document.getElementById("mySidenav").style['margin-top']="60px"
                }
                else{
                    document.getElementById("mySidenav").style['width']="0"
                    document.getElementById("user-name-email").style["display"]="none"
                    document.getElementById("top").style['color']="black"
                    document.getElementById("top").style['background-color']="white"
                    document.getElementById("mySidenav").style['margin-top']="0px"    
                }
            }

    </script>
    {% block page_js %}
    {% endblock %}
    {% include 'web/components/messages-js.html' %}
</body>
</html>

templates/app/list.html
{% extends "app/layout.html" %}

{% block title %}
    Lead List
{% endblock %}

{% block body %}
<style type="text/css">
    #scrape{
        background-color: #325ae7;
        color: white
    }
    </style>
    <div id="top2">
        <h2>Search for <u>{{industry}}</u>{% if industry == "E-Commerce" %} stores that sell {%else%} in {%endif%}<u>{{location}}</u></h2>
        <p>Max num. companies: <b>{{leads}}</b>, Max num. contacts: <b>{{contacts}}</b><br>Job titles: {% for job in job_titles %}<i>{{job}}</i>{{ forloop.last|yesno:",&#44;"|safe }} {%endfor%}</p>
    </div>
    {% comment %} <div id="loading"></div> {% endcomment %}
    <div id="section-csv">
        <span id="loading" style="display:block">Searching for new leads ...</span>
        <span id="leads-found-successfully" style="display:none">
            <b><span id="num_of_target"></span>
            verified emails found!</b>
            <span id="extraleads" {% if count > target %} style="display:inline"{%else%}style="display:none"{%endif%}>(The {{extra}} extra leads are free of charge!)</span> 
            <span id="refund" {% if count < target %} style="display:inline"{%else%}style="display:none"{%endif%}>(The remaining {% widthratio extra 1 -1 %} credits have been refunded.)</span> 
            <br>
            <a href="{% url "get_csv" id %}">Download CSV</a>
            <br>
            <i>All data columns: Product, Company Website, Contact Name, Contact Title, Contact LinkedIn, Contact Email, Verified</i></span>
    </div>
    <div id="loading-bar"><br><progress class="progress is-small is-info" max="100">15%</progress></div>
    <div class="section-inner">
    <div id="searchResDiv">
        {% include 'app/table.html' %}
    </div>
    </div>
    <script type="text/javascript">
        {% comment %} window.onload = function(){ {% endcomment %}
            var a = 0
            $.ajax({
                type: 'GET',
                url: "{% url 'scrape_status' id %}",
                success: function (response) {
                    a = response["stage"]
                    if(a==4){
                        $("#section-csv").css({"backgroundColor":" #daf5e1"});
                        $("#loading").hide()
                        $("#loading-bar").hide()
                        $("#leads-found-successfully").show()
                        $("#num_of_target").html(response["count"]+"/"+response["target"])
                    }
                    else{
                        //$("#section-csv").css({"backgroundColor":"white"});
                        if(a==0){
                            $("#loading").html("Searching for new leads...")
                        }
                        else if(a==1){
                            $("#loading").html("Finding decision maker names...")
                        }
                        else if(a==2){
                            $("#loading").html("Scraping emails and verifying their deliverability...")
                        }
                        else if(a==3){
                            $("#loading").html("Processing results...")
                        }
                        loadInterval = setInterval(function(){$.ajax({
                            type: 'GET',
                            url: "{% url 'scrape_status' id %}",
                            success: function (response) {
                                if(response["stage"]!=a){
                                    console.log(a)
                                    console.log(response["stage"])
                                    a=response["stage"]
                                    if(a==4){
                                        $("#refund").hide()
                                        $("#section-csv").css("background-color"," #daf5e1");
                                        $("#loading").hide()
                                        $("#loading-bar").hide()
                                        $("#leads-found-successfully").show()
                                        $("#num_of_target").html(response["count"]+"/"+response["target"])
                                        if(response["count"]>response["target"]){
                                            $("#extraleads").show()
                                            $("#extraleads").html("(The "+(response["count"]-response["target"])+" extra leads are free of charge!)")
                                        }
                                        else if(response["count"]<response["target"]){
                                            $("#refund").show()
                                        }
                                        $("#searchResDiv").load("{% url 'list' id=id %}")
                                        clearInterval(loadInterval)
                                    }
                                    else if(a==0){
                                        $("#leads-found-successfully").hide()
                                        $("#loading").show()
                                        $("#loading").html("Searching for new leads...")
                                        $("#searchResDiv").load("{% url 'list' id=id %}")
                                    }
                                    else if(a==1){
                                        $("#loading").html("Finding decision maker names...")
                                        $("#searchResDiv").load("{% url 'list' id=id %}")
                                    }
                                    else if(a==2){
                                        $("#loading").html("Scraping emails and verifying their deliverability...")
                                        $("#searchResDiv").load("{% url 'list' id=id %}")
                                    }
                                    else if(a==3){
                                        $("#loading").html("Processing results...")
                                        $("#searchResDiv").load("{% url 'list' id=id %}")
                                    }
                                }
                                else if(a==2){
                                    $("#searchResDiv").load("{% url 'list' id=id %}")  
                                }
                            }
                        })},1000)
                    }
                }
            })

            
        {% comment %} } {% endcomment %}
    </script>
{% endblock %}

templates/app/lists.html
{% extends "app/layout.html" %}

{% block title %}
    Scrape Emails
{% endblock %}

{% block body %}
<style type="text/css">
    #scrape{
        background-color: #325ae7;
        color: white
    }
    </style>
    <div id="top2">
        <h1>Your Lead Lists</h1>
        <p>View and download your verified emails.</p>
    </div>
    <div class="section-inner" id="listDiv"> 
        {% include 'app/lists_table.html' %}
    {% comment %} <table id="searches">
        <tr>
            <th>id</th>
            <th>Industry</th>
            <th>Location</th>
            <th>Emails Found</th>
            <th>Status</th>
        </tr>
        {% for search in searches %}
        <tr>
            <td><a href="{% url "list" search.id %}">list_{{search.id}}</a></td>
            <td>{{ search.industry }}</td>
            <td>{{ search.location }}</td>
            <td>
                {% if search.count == 0 %}
                    -
                {% else %}
                    {{ search.count }}
                {% endif %}
            </td>
            <td>{% if search.status == 4 %}
                    Complete
                {% elif search.status == 3 %}
                    Processing... <img style="width:16px; vertical-align:baseline" src="https://i.gifer.com/ZZ5H.gif">
                {% elif search.status == 2 %}
                    Scraping emails... <img style="width:16px; vertical-align:baseline" src="https://i.gifer.com/ZZ5H.gif">
                {% elif search.status == 1 %}
                    Finding contacts... <img style="width:16px; vertical-align:baseline" src="https://i.gifer.com/ZZ5H.gif">
                {% elif search.status == 0 %}
                    Finding leads... <img style="width:16px; vertical-align:baseline" src="https://i.gifer.com/ZZ5H.gif">
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </table> {% endcomment %}
</div>
<script type="text/javascript">
    setInterval(function(){$("#listDiv").load("{% url 'lists' %}")},1000)
</script>
{% endblock %}

templates/app/lists_table.html
<table id="searches">
    <tr>
        <th>id</th>
        <th>Industry</th>
        <th>Location</th>
        <th>Emails Found</th>
        <th>Status</th>
    </tr>
    {% for search in searches %}
    <tr>
        <td><a href="{% url "list" search.id %}">list_{{search.id}}</a></td>
        <td>{{ search.industry }}</td>
        <td>{{ search.location }}</td>
        <td>
            {% if search.count == 0 %}
                -
            {% else %}
                {{ search.count }}
            {% endif %}
        </td>
        <td>{% if search.status == 4 %}
                Complete
            {% elif search.status == 3 %}
                Processing... <img style="width:16px; vertical-align:baseline" src="https://i.gifer.com/ZZ5H.gif">
            {% elif search.status == 2 %}
                Scraping emails... <img style="width:16px; vertical-align:baseline" src="https://i.gifer.com/ZZ5H.gif">
            {% elif search.status == 1 %}
                Finding contacts... <img style="width:16px; vertical-align:baseline" src="https://i.gifer.com/ZZ5H.gif">
            {% elif search.status == 0 %}
                Finding leads... <img style="width:16px; vertical-align:baseline" src="https://i.gifer.com/ZZ5H.gif">
            {% endif %}
        </td>
    </tr>
    {% endfor %}
</table>

templates/app/table.html
<table id="searchResults">
    <tr>
        <th>Industry</th>
        <th>{% if industry == "E-Commerce" %}Product{%else%}Location{%endif%}</th>
        <th>Company</th>
        <th>Contact Name</th>
        <th>Contact Title</th>
        {% comment %} <th>Snippet</th> {% endcomment %}
        <th>Double-Verified Email</th>
        {% comment %} <th>Address</th>
        <th>Link</th>
        <th>LinkedIn</th>
        <th>Count</th> {% endcomment %}
        {% comment %} <th>Order</th> {% endcomment %}
        {% comment %} <th>Name</th>
        <th>Title</th>
        <th>LinkedIn</th>
        <th>Verified Email</th>
        <th>Phone</th>
        <th>Valid</th>
        <th>ID</th> {% endcomment %}
    </tr>
    {% for result in searchResults %}
    {% if result.num_leads == 0%}
    {% if result.result.processed == False %}
    <tr style="background-color: whitesmoke">
{% else %} 
    <tr>
{% endif %}
    {% comment %} <td>{{result.search.industry}}</td>   {% endcomment %}
    
    <td>{% if result.result.search.industry == "ecom" %}E-Commerce{%else%}{{result.result.category}}{%endif%}</td>
    <td>{{result.result.search.location}}</td>   
    <td><a class="table-link" href="http://www.{{result.result.domain}}" target="_blank" rel="noopener noreferrer">{{result.result.title}}</a></td>
    <td></td>
    <td></td>
    <td></td>
    </tr>
    {% else %}
    {% for lead in result.leads %}
    {% if result.result.processed == False %}
        <tr style="background-color: whitesmoke">
    {% else %} 
        <tr {% if forloop.first %}style="border-top:2px solid #ddd"{% endif %}>
    {% endif %}
        {% comment %} <td>{{result.search.industry}}</td>   {% endcomment %}
        
        <td>{% if forloop.first %}{% if result.result.search.industry == "E-Commerce" %}E-Commerce{%else%}{{result.result.category}}{%endif%}{% endif %}</td>
        <td>{% if forloop.first %}{{result.result.search.location}}{% endif %}</td>   
        <td>{% if forloop.first %}<a class="table-link" href="http://www.{{result.result.domain}}" target="_blank" rel="noopener noreferrer">{{result.result.title}}</a>{% endif %}</td>
        <td>{{lead.name}}</td>
        <td>{{lead.title}}</td>
        {% if lead.verified_email != None %}
        <td style="background-color:#daf5e1">
        {% else %}
        <td>
        {% endif %}
            {{lead.verified_email}}
        </td>
    </tr>
    {% endfor %}
    {%endif%}
    {% endfor %}
</table>